' fork from https://github.com/indieatom/docsify-puml/blob/main/src/skins/default.pu

skinparam defaultFontName "-apple-system"
skinparam defaultFontSize 12
skinparam sequenceMessageAlign center
skinparam monochrome false
skinparam shadowing false

skinparam activity {
	ArrowColor Black
	BackgroundColor White
	BorderColor Black
	BorderThickness 1
}

skinparam actor {
	BackgroundColor White
	BorderColor Black
}

skinparam usecase {
	ArrowColor Black
	BackgroundColor White
	BorderColor Black
	BorderThickness 1
}

skinparam class {
	ArrowColor Black
	BackgroundColor White
	BorderColor Black
	BorderThickness 1
}


skinparam object {
	ArrowColor Black
	BackgroundColor White
	BorderColor Black
}

skinparam package {
	BackgroundColor White
	BorderColor Black
}

'TODO stereotype

skinparam component {
	BackgroundColor White
	InterfaceBackgroundColor White
	BorderColor Black
	InterfaceBorderColor Black
}

skinparam note {
	BackgroundColor White
	BorderColor Black
}

skinparam state {
	ArrowColor Black
	BackgroundColor White
	BorderColor Black
}

skinparam sequence {
	ArrowColor Black
	BackgroundColor White
	ParticipantBackgroundColor White
	BorderColor Black
	LifeLineBorderColor Black
	ParticipantBorderColor Black
	BoxLineColor Black
}

skinparam interface {
	BackgroundColor White
	BorderColor Black
}

' ----------------------
' --- custom changes ---
' ----------------------

skinparam card {
	BackgroundColor WhiteSmoke
	BorderColor WhiteSmoke
    FontStyle normal
}

skinparam rectangle {
	BackgroundColor #B1DDFA
    BorderThickness 1
    RoundCorner 5
}

skinparam storage {
	BorderColor Gray
    BorderThickness 1
    FontStyle italic
    RoundCorner 5
}
